import mongoose from 'mongoose';

const billSchema = new mongoose.Schema({
  // id_factura is automatically generated by MongoDB as _id
  orderId: { type: mongoose.Schema.Types.ObjectId, ref: 'Order', required: true }, // id_pedido
  customerId: { type: mongoose.Schema.Types.ObjectId, ref: 'Customer', required: true }, // id_cliente
  issueDate: { type: Date, required: true, default: Date.now }, // fecha_emision
  paymentDetails: { type: String, required: true }, // detalles_pago
  total: { type: Number, required: true }, // total
  paymentMethod: { type: String, required: true } // metodo_pago
}, {
  timestamps: true
});

const Bill = mongoose.model('Bill', billSchema);
export default Bill;
